name: Build and store

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - development
          - staging
          - production
        description: 'Select the deployment environment'
        required: true 
        default: development

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-dist-${{ github.event.inputs.environment }}
          path: dist
      - name: Verify artifact
        run: |
          ls -la dist
      - name: Trigger Repo B workflow to read artifact
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: bednayb/gitActions
          event-type: read-repo-a-artifact
          client-payload: '{"env": "${{ github.event.inputs.environment }}"}'
